/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AnmeldenRouteImport } from './routes/anmelden'
import { Route as DatenschutzRouteImport } from './routes/datenschutz'
import { Route as ImpressumRouteImport } from './routes/impressum'
import { Route as KontaktRouteImport } from './routes/kontakt'
import { Route as AuthenticatedAssistentRouteImport } from './routes/_authenticated/assistent'
import { Route as AuthenticatedEinstellungenRouteImport } from './routes/_authenticated/einstellungen'
import { Route as AuthenticatedNachrichtenRouteImport } from './routes/_authenticated/nachrichten'
import { Route as AuthenticatedNeuRouteImport } from './routes/_authenticated/neu'
import { Route as AuthenticatedStartRouteImport } from './routes/_authenticated/start'
import { Route as AuthenticatedArtikelArtikelIdRouteImport } from './routes/_authenticated/artikel.$artikelId'
import { Route as AuthenticatedVerbindungMarktplatzRouteImport } from './routes/_authenticated/verbindung.$marktplatz'
import { Route as ApiPublicAssistentSkriptRouteImport } from './routes/api/public/assistent/skript'
import { Route as ApiPublicUebergabeTokenRouteImport } from './routes/api/public/uebergabe/$token'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AnmeldenRoute = AnmeldenRouteImport.update({
  id: '/anmelden',
  path: '/anmelden',
  getParentRoute: () => rootRouteImport,
} as any)
const DatenschutzRoute = DatenschutzRouteImport.update({
  id: '/datenschutz',
  path: '/datenschutz',
  getParentRoute: () => rootRouteImport,
} as any)
const ImpressumRoute = ImpressumRouteImport.update({
  id: '/impressum',
  path: '/impressum',
  getParentRoute: () => rootRouteImport,
} as any)
const KontaktRoute = KontaktRouteImport.update({
  id: '/kontakt',
  path: '/kontakt',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAssistentRoute = AuthenticatedAssistentRouteImport.update({
  id: '/assistent',
  path: '/assistent',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedEinstellungenRoute =
  AuthenticatedEinstellungenRouteImport.update({
    id: '/einstellungen',
    path: '/einstellungen',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedNachrichtenRoute =
  AuthenticatedNachrichtenRouteImport.update({
    id: '/nachrichten',
    path: '/nachrichten',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedNeuRoute = AuthenticatedNeuRouteImport.update({
  id: '/neu',
  path: '/neu',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedStartRoute = AuthenticatedStartRouteImport.update({
  id: '/start',
  path: '/start',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedArtikelArtikelIdRoute =
  AuthenticatedArtikelArtikelIdRouteImport.update({
    id: '/artikel/$artikelId',
    path: '/artikel/$artikelId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedVerbindungMarktplatzRoute =
  AuthenticatedVerbindungMarktplatzRouteImport.update({
    id: '/verbindung/$marktplatz',
    path: '/verbindung/$marktplatz',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const ApiPublicAssistentSkriptRoute =
  ApiPublicAssistentSkriptRouteImport.update({
    id: '/api/public/assistent/skript',
    path: '/api/public/assistent/skript',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicUebergabeTokenRoute = ApiPublicUebergabeTokenRouteImport.update({
  id: '/api/public/uebergabe/$token',
  path: '/api/public/uebergabe/$token',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/anmelden': typeof AnmeldenRoute
  '/datenschutz': typeof DatenschutzRoute
  '/impressum': typeof ImpressumRoute
  '/kontakt': typeof KontaktRoute
  '/assistent': typeof AuthenticatedAssistentRoute
  '/einstellungen': typeof AuthenticatedEinstellungenRoute
  '/nachrichten': typeof AuthenticatedNachrichtenRoute
  '/neu': typeof AuthenticatedNeuRoute
  '/start': typeof AuthenticatedStartRoute
  '/artikel/$artikelId': typeof AuthenticatedArtikelArtikelIdRoute
  '/verbindung/$marktplatz': typeof AuthenticatedVerbindungMarktplatzRoute
  '/api/public/assistent/skript': typeof ApiPublicAssistentSkriptRoute
  '/api/public/uebergabe/$token': typeof ApiPublicUebergabeTokenRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/anmelden': typeof AnmeldenRoute
  '/datenschutz': typeof DatenschutzRoute
  '/impressum': typeof ImpressumRoute
  '/kontakt': typeof KontaktRoute
  '/assistent': typeof AuthenticatedAssistentRoute
  '/einstellungen': typeof AuthenticatedEinstellungenRoute
  '/nachrichten': typeof AuthenticatedNachrichtenRoute
  '/neu': typeof AuthenticatedNeuRoute
  '/start': typeof AuthenticatedStartRoute
  '/artikel/$artikelId': typeof AuthenticatedArtikelArtikelIdRoute
  '/verbindung/$marktplatz': typeof AuthenticatedVerbindungMarktplatzRoute
  '/api/public/assistent/skript': typeof ApiPublicAssistentSkriptRoute
  '/api/public/uebergabe/$token': typeof ApiPublicUebergabeTokenRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/anmelden': typeof AnmeldenRoute
  '/datenschutz': typeof DatenschutzRoute
  '/impressum': typeof ImpressumRoute
  '/kontakt': typeof KontaktRoute
  '/_authenticated/assistent': typeof AuthenticatedAssistentRoute
  '/_authenticated/einstellungen': typeof AuthenticatedEinstellungenRoute
  '/_authenticated/nachrichten': typeof AuthenticatedNachrichtenRoute
  '/_authenticated/neu': typeof AuthenticatedNeuRoute
  '/_authenticated/start': typeof AuthenticatedStartRoute
  '/_authenticated/artikel/$artikelId': typeof AuthenticatedArtikelArtikelIdRoute
  '/_authenticated/verbindung/$marktplatz': typeof AuthenticatedVerbindungMarktplatzRoute
  '/api/public/assistent/skript': typeof ApiPublicAssistentSkriptRoute
  '/api/public/uebergabe/$token': typeof ApiPublicUebergabeTokenRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/anmelden'
    | '/datenschutz'
    | '/impressum'
    | '/kontakt'
    | '/assistent'
    | '/einstellungen'
    | '/nachrichten'
    | '/neu'
    | '/start'
    | '/artikel/$artikelId'
    | '/verbindung/$marktplatz'
    | '/api/public/assistent/skript'
    | '/api/public/uebergabe/$token'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/anmelden'
    | '/datenschutz'
    | '/impressum'
    | '/kontakt'
    | '/assistent'
    | '/einstellungen'
    | '/nachrichten'
    | '/neu'
    | '/start'
    | '/artikel/$artikelId'
    | '/verbindung/$marktplatz'
    | '/api/public/assistent/skript'
    | '/api/public/uebergabe/$token'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/anmelden'
    | '/datenschutz'
    | '/impressum'
    | '/kontakt'
    | '/_authenticated/assistent'
    | '/_authenticated/einstellungen'
    | '/_authenticated/nachrichten'
    | '/_authenticated/neu'
    | '/_authenticated/start'
    | '/_authenticated/artikel/$artikelId'
    | '/_authenticated/verbindung/$marktplatz'
    | '/api/public/assistent/skript'
    | '/api/public/uebergabe/$token'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AnmeldenRoute: typeof AnmeldenRoute
  DatenschutzRoute: typeof DatenschutzRoute
  ImpressumRoute: typeof ImpressumRoute
  KontaktRoute: typeof KontaktRoute
  ApiPublicAssistentSkriptRoute: typeof ApiPublicAssistentSkriptRoute
  ApiPublicUebergabeTokenRoute: typeof ApiPublicUebergabeTokenRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/anmelden': {
      id: '/anmelden'
      path: '/anmelden'
      fullPath: '/anmelden'
      preLoaderRoute: typeof AnmeldenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/datenschutz': {
      id: '/datenschutz'
      path: '/datenschutz'
      fullPath: '/datenschutz'
      preLoaderRoute: typeof DatenschutzRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/impressum': {
      id: '/impressum'
      path: '/impressum'
      fullPath: '/impressum'
      preLoaderRoute: typeof ImpressumRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kontakt': {
      id: '/kontakt'
      path: '/kontakt'
      fullPath: '/kontakt'
      preLoaderRoute: typeof KontaktRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/assistent': {
      id: '/_authenticated/assistent'
      path: '/assistent'
      fullPath: '/assistent'
      preLoaderRoute: typeof AuthenticatedAssistentRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/einstellungen': {
      id: '/_authenticated/einstellungen'
      path: '/einstellungen'
      fullPath: '/einstellungen'
      preLoaderRoute: typeof AuthenticatedEinstellungenRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/nachrichten': {
      id: '/_authenticated/nachrichten'
      path: '/nachrichten'
      fullPath: '/nachrichten'
      preLoaderRoute: typeof AuthenticatedNachrichtenRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/neu': {
      id: '/_authenticated/neu'
      path: '/neu'
      fullPath: '/neu'
      preLoaderRoute: typeof AuthenticatedNeuRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/start': {
      id: '/_authenticated/start'
      path: '/start'
      fullPath: '/start'
      preLoaderRoute: typeof AuthenticatedStartRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/artikel/$artikelId': {
      id: '/_authenticated/artikel/$artikelId'
      path: '/artikel/$artikelId'
      fullPath: '/artikel/$artikelId'
      preLoaderRoute: typeof AuthenticatedArtikelArtikelIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/verbindung/$marktplatz': {
      id: '/_authenticated/verbindung/$marktplatz'
      path: '/verbindung/$marktplatz'
      fullPath: '/verbindung/$marktplatz'
      preLoaderRoute: typeof AuthenticatedVerbindungMarktplatzRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/public/assistent/skript': {
      id: '/api/public/assistent/skript'
      path: '/api/public/assistent/skript'
      fullPath: '/api/public/assistent/skript'
      preLoaderRoute: typeof ApiPublicAssistentSkriptRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/uebergabe/$token': {
      id: '/api/public/uebergabe/$token'
      path: '/api/public/uebergabe/$token'
      fullPath: '/api/public/uebergabe/$token'
      preLoaderRoute: typeof ApiPublicUebergabeTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAssistentRoute: typeof AuthenticatedAssistentRoute
  AuthenticatedEinstellungenRoute: typeof AuthenticatedEinstellungenRoute
  AuthenticatedNachrichtenRoute: typeof AuthenticatedNachrichtenRoute
  AuthenticatedNeuRoute: typeof AuthenticatedNeuRoute
  AuthenticatedStartRoute: typeof AuthenticatedStartRoute
  AuthenticatedArtikelArtikelIdRoute: typeof AuthenticatedArtikelArtikelIdRoute
  AuthenticatedVerbindungMarktplatzRoute: typeof AuthenticatedVerbindungMarktplatzRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAssistentRoute: AuthenticatedAssistentRoute,
  AuthenticatedEinstellungenRoute: AuthenticatedEinstellungenRoute,
  AuthenticatedNachrichtenRoute: AuthenticatedNachrichtenRoute,
  AuthenticatedNeuRoute: AuthenticatedNeuRoute,
  AuthenticatedStartRoute: AuthenticatedStartRoute,
  AuthenticatedArtikelArtikelIdRoute: AuthenticatedArtikelArtikelIdRoute,
  AuthenticatedVerbindungMarktplatzRoute:
    AuthenticatedVerbindungMarktplatzRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AnmeldenRoute: AnmeldenRoute,
  DatenschutzRoute: DatenschutzRoute,
  ImpressumRoute: ImpressumRoute,
  KontaktRoute: KontaktRoute,
  ApiPublicAssistentSkriptRoute: ApiPublicAssistentSkriptRoute,
  ApiPublicUebergabeTokenRoute: ApiPublicUebergabeTokenRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
